language: python

env:
  - DJANGO="django==1.6"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.4.10"
  - DJANGO="django==1.3.7"

install: pip install tox --use-mirrors

script: tox

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.10"
    - python: "3.2"
      env: DJANGO="django==1.3.7"
    - python: "3.3"
      env: DJANGO="django==1.4.10"
    - python: "3.3"
      env: DJANGO="django==1.3.7"
