language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.6.5"
  - DJANGO="django==1.5.8"
  - DJANGO="django==1.4.13"

install:
  - pip install $DJANGO
  - pip install pytest-django==2.6.1
  - pip install flake8==2.2.2
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install django-oauth2-provider==0.2.4; fi"
  - export PYTHONPATH=.

script:
  - ./runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.13"
    - python: "3.3"
      env: DJANGO="django==1.4.13"
    - python: "3.4"
      env: DJANGO="django==1.4.13"
